#!/usr/bin/env bash
# Usage: amzn terminate environment [app]
# Summary: wrap amzn-ship's terminate command
# Help: Destroys the ASG, ELB, etc. with amzn-ship
#
#    amzn terminate staging
#    amzn terminate staging killer-app
#
# The last argument, [app], is optional, and defaults to the AMZN_APP_NAME environment variable or the name of the current directory if not given.
#
# NOTE: You must set AMZN_SHIP_DIR in your environment to point to your amzn-ship directory.

set -e
[ -n "$AMZN_DEBUG" ] && set -x

source "$_AMZN_ROOT/libexec/shared"

run_ship_command terminate $@
