#!/usr/bin/env bash
# Usage: amzn update-asg [-e environment] [-a app]
# Summary: wrap amzn-ship's update-asg command
# Help: Recreate the launch configuration for the ASG with the latest config
#
#    amzn update-asg
#    amzn update-asg -e staging
#    amzn update-asg -e staging -a killer-app
#
# The arguments are optional:
#
#    [-e environment] defaults to '-e staging' if not given
#    [-a app] defaults to the AMZN_APP_NAME environment variable if set or the name of the current directory
#
# The new ami id must be in the AMI environment variable.

source "$_AMZN_ROOT/libexec/shared"

run_ship_command update-asg $@
