#!/usr/bin/env bash
# Usage: amzn setup [-e environment] [-a app]
# Summary: wrap amzn-ship's setup command
# Help: Sets up an ASG, ELB, etc. with amzn-ship
#
#    amzn setup
#    amzn setup -e staging
#    amzn setup -e staging -a killer-app
#
# The arguments are optional:
#
#    [-e environment] defaults to '-e staging' if not given
#    [-a app] defaults to the AMZN_APP_NAME environment variable if set or the name of the current directory

source "$_AMZN_ROOT/libexec/shared"

run_ship_command setup $@
