#!/usr/bin/env bash
# Usage: amzn setup environment [app]
# Summary: wrap amzn-ship's setup command
# Help: Sets up an ASG, ELB, etc. with amzn-ship
#
#    amzn setup staging
#    amzn setup staging killer-app
#
# The last argument, [app], is optional, and defaults to the AMZN_APP_NAME environment variable or the name of the current directory if not given.
#
# NOTE: You must set AMZN_SHIP_DIR in your environment to point to your amzn-ship directory.

set -e
[ -n "$AMZN_DEBUG" ] && set -x

source "$_AMZN_ROOT/libexec/shared"

run_ship_command setup $@
