#!/usr/bin/env bash
# Usage: amzn terminate [-e environment] [-a app]
# Summary: wrap amzn-ship's terminate command
# Help: Destroys the ASG, ELB, etc. with amzn-ship
#
#    amzn terminate
#    amzn terminate -e staging
#    amzn terminate -e staging -a killer-app
#
# The arguments are optional:
#
#    [-e environment] defaults to '-e staging' if not given
#    [-a app] defaults to the AMZN_APP_NAME environment variable if set or the name of the current directory

source "$_AMZN_ROOT/libexec/shared"

run_ship_command terminate $@
